# Form implementation generated from reading ui file 'SymLinkGen.ui'
#
# UI Generated by: PyQt5 UI code generator 5.15.3
#
# Written By Timothy Potter (HeOfLittleSleep) with python 3.9.2

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QMessageBox

def on_click(self):
    print("oh hey it works hooray and stuff")


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("SymLinkGen")
        MainWindow.resize(183, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 160, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("SymName")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("SymTarget")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("SymLoc")
        self.verticalLayout.addWidget(self.lineEdit_3)

        GenLinkBtn = QtWidgets.QPushButton(self.centralwidget)
        GenLinkBtn.setGeometry(QtCore.QRect(10, 180, 158, 23))
        GenLinkBtn.setObjectName("BtnGenLink")
        GenLinkBtn.setText("Generate SymLink")
        GenLinkBtn.clicked.connect(on_click)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 183, 21))
        self.menubar.setObjectName("menubar")
        self.menuSymLink_generator = QtWidgets.QMenu(self.menubar)
        self.menuSymLink_generator.setObjectName("menuSymLink_generator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSymLink_generator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SymLink Generator"))
        self.label.setText(_translate("MainWindow", "SymLink Name"))
        self.label_2.setText(_translate("MainWindow", "SymLink Target"))
        self.label_3.setText(_translate("MainWindow", "SymLink Location"))
        # GenLinkBtn.setText(_translate("MainWindow", "Generate SymLink"))
        self.menuSymLink_generator.setTitle(_translate("MainWindow", "SymLink Generator"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
